apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: securebox

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres-deployment.yaml
  - redis-deployment.yaml
  - api-deployment.yaml
  - portal-deployment.yaml
  - nginx-configmap.yaml
  - nginx-deployment.yaml

commonLabels:
  app.kubernetes.io/name: securebox
  app.kubernetes.io/managed-by: kustomize

images:
  - name: ${REGISTRY_URL}/securebox/api
    newTag: latest
  - name: ${REGISTRY_URL}/securebox/portal
    newTag: latest

